name: 'clickup-get-tasks'
description: 'Github action to fetch tasks from Clickup via the API'
author: 'Tjitse-E'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  clickup_token:
    description: Your clickup token
    required: true
  clickup_custom_task_ids:
    description: A list of custom task IDS of which you want to change the status
    required: true
  clickup_team_id:
    description: Your clickup team id
    required: true
  response_fields:
    description: Fields that are in the response
    required: false
  convert_quotes:
    description: Convert single and double quotes to html
    required: false
    default: true
outputs:
  clickup_tasks:
    description: JSON object containing the clickup task info
  invalid_tasks:
    description: JSON object containing the clickup tasks that could not be found
